config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'
  devise_for :users

  resources :events do
    get 'stream', on: :member
  end
  resources :token, :controller=>"token" do
    resources :streams
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_uniqueness_of :event_id
  validates_presence_of :session_id
  before_create :generate_event_id

  def self.create_with_session_id(session_id)
    create_with_event_id(session_id: session_id)
  end

  def self.create_with_event_id(args = {})
    begin
      self.create!(args)
    rescue ActiveRecord::RecordNotUnique
      generate_event_id
      retry
    end
  end

  def to_param
    event_id
  end

  def token
    @token ||= OPENTOK.generate_token(session_id, role: :publisher)
  end

  private

  def generate_event_id
    self.event_id = ('A'..'Z').to_a.sample(6).join
  end
end

app/models/event_connection.rb
class EventConnection
  include ActiveModel::Serialization

  attr_accessor :event, :role
  private :event
  delegate :event_id, :session_id, to: :event

  def initialize(event, role = nil)
    @event = event
    @session_id = event.session_id
    @role = role || :publisher
  end

  def token
    @token ||= OPENTOK.generate_token(session_id, role: role)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/not_found.rb
module NotFound
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
  end

  private

  def not_found
    head :not_found
  end

end

app/controllers/token_controller.rb
class TokenController < ApplicationController
  skip_before_action :verify_authenticity_token
  include NotFound

  def show
    event = Event.find_by_event_id!(params[:id])
    render json: EventConnection.new(event, params[:role])
  end

  def create
    opentok_session = OPENTOK.create_session :media_mode => :routed
    opentok_session_id = opentok_session.session_id

    event = Event.create_with_session_id(opentok_session_id)
    render json: EventConnection.new(event, params[:role])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/helpers/token_helper.rb
module TokenHelper
end

app/views/events/index.html.haml
.row
  .columns
    = button_to "Create a Session", events_path, class: 'button'
.row
  .columns
    = form_tag events_path, method: :get do
      = text_field_tag :id
      = submit_tag "Join", class: 'button'

app/views/events/show.html.haml
:javascript
  var apiKey = '#{ENV['OPENTOK_API_KEY']}';
  var sessionId = '#{@event.session_id}';
  var token = '#{@token}';

  // Initialize an OpenTok Session object
  var session = TB.initSession(sessionId);

  // Initialize a Publisher, and place it into the element with id="publisher"
  var publisher = TB.initPublisher(apiKey, 'publisher', {publishVideo: false});

  // Attach event handlers
  session.on({
  // This function runs when another client publishes a stream (eg. session.publish())
  streamCreated: function(event) {
  // Create a container for a new Subscriber, assign it an id using the streamId, put it inside
  // the element with id="subscribers"
  var subContainer = $(document.createElement('ul'));
  subContainer.attr('id', 'stream-' + event.stream.streamId);
  subContainer.addClass('stream');
  subContainer.data('streamId', event.stream.streamId)
  $('#subscribers').append(subContainer);
  // Subscribe to the stream that caused this event, put it inside the container we just made
  session.subscribe(event.stream, subContainer);
  }
  });

  // Connect to the Session using the 'apiKey' of the application and a 'token' for permission
  session.connect(apiKey, token);

#publisher
.row
  .columns.text-right
    = "Session Code: #{@event.session_code}"
.row
  .columns
    %ul#subscribers
      - 6.times do |n|
        %li.stream{ data: { streamId: n } }
          %img{ src: 'https://placeimg.com/640/480/arch' }

app/views/events/stream.html.haml
.row
  .columns.text-right
    = "Session Code: #{@event.session_code}"
.row
  .medium-2.columns
    = link_to "<< Back", @event, class: 'button'
    .row
      .columns
        .range-slider.vertical-range{"data-options" => "vertical: true;", "data-slider" => ""}
          %span.range-slider-handle{:role => "slider", :tabindex => "0"}
          %span.range-slider-active-segment
          %input{:type => "hidden"}/
  .medium-7.columns#presenter
    %img{ src: 'https://placeimg.com/1200/1600/people' }
  .medium-3.columns
    .row
      .columns
        %label Archive
        %input#on{:name => "on", :type => "radio", :value => "on"}/
        %label{:for => "on"} On
        %input#off{:name => "off", :type => "radio", :value => "off"}/
        %label{:for => "off"} Off
    .row
      .columns
        = link_to "Full Screen", "#", class: 'button'
    .row
      .columns
        = link_to "Capture", "#", class: 'button'
    .row
      .columns
        %ul.small-block-grid-1
          - 3.times do
            %li
              %img{ src: 'https://placeimg.com/640/480/arch' }
.row
  .columns
    %ul#bottom_streams.small-block-grid-6
      - 6.times do
        %li
          %img{ src: 'https://placeimg.com/640/480/arch' }
          .progress.radius
            %span.meter{style: "width: #{[10, 20, 30, 40, 60, 70].sample}%"}

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Home', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        Menu
  .top-bar-section
    %ul
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Agility Server'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Agility Server'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{ src: "//static.opentok.com/v2/js/opentok.min.js" }
    = csrf_meta_tags
  %body
    %header
      =# render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/visitors/index.html.erb
<h3>Welcome</h3>